import { registerDecorator, ValidationOptions, ValidationArguments } from 'class-validator';

/**
 * Custom validator for CUID (Collision-resistant Unique IDentifier)
 * CUIDs are generated by Prisma's @default(cuid()) and have the format:
 * - Start with 'c'
 * - Followed by 24 lowercase alphanumeric characters
 * - Example: cmgzjb71a0003aexl2yrhmcbf
 *
 * This validator ensures DTOs accept CUID format instead of requiring UUID format.
 */
export function IsCuid(validationOptions?: ValidationOptions) {
  return function (object: Object, propertyName: string) {
    registerDecorator({
      name: 'isCuid',
      target: object.constructor,
      propertyName: propertyName,
      options: validationOptions,
      validator: {
        validate(value: any, args: ValidationArguments) {
          if (typeof value !== 'string') {
            return false;
          }
          // CUID format: starts with 'c', followed by 24 alphanumeric characters
          // Total length: 25 characters
          return /^c[a-z0-9]{24}$/i.test(value);
        },
        defaultMessage(args: ValidationArguments) {
          return `${args.property} must be a valid CUID (Collision-resistant Unique IDentifier)`;
        },
      },
    });
  };
}

/**
 * Validator that accepts both CUID and UUID formats
 * Use this for fields that might receive either format for backward compatibility
 */
export function IsCuidOrUuid(validationOptions?: ValidationOptions) {
  return function (object: Object, propertyName: string) {
    registerDecorator({
      name: 'isCuidOrUuid',
      target: object.constructor,
      propertyName: propertyName,
      options: validationOptions,
      validator: {
        validate(value: any, args: ValidationArguments) {
          if (typeof value !== 'string') {
            return false;
          }
          // Check CUID format
          const isCuid = /^c[a-z0-9]{24}$/i.test(value);
          // Check UUID format (with or without hyphens)
          const isUuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(value) ||
                        /^[0-9a-f]{32}$/i.test(value);

          return isCuid || isUuid;
        },
        defaultMessage(args: ValidationArguments) {
          return `${args.property} must be a valid CUID or UUID`;
        },
      },
    });
  };
}
